baseURL = "https://test.marktaguiad.dev/"
DefaultContentLanguage = "en"
languageCode = "en-us"
title = "Mark Taguiad"
copyright = "marktaguiad.dev"
theme = "hugo-theme-diary"

# Generate sitemap in the public folder
[sitemap]
  changefreq = "always"
  filename = "sitemap.xml"
  priority = 0.5

# Google Analytics
[services]
  [services.googleAnalytics]
    id = "G-XCHH9NNNBX"  # Your Google Analytics ID

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4

[params]
subtitle = "A less serious version of my website."
enableGitalk = false
enableGiscus = true

# Microsoft Clarity (https://clarity.microsoft.com/) is a free user behavior recording and analytics tool
clarity = "abcdefghzd"

# Twitter Card and Open Graph settings
enableOpenGraph = true
enableTwitterCards = true
title = "My Blog" # will set 'og:site_name'
description = "My HomePage Description"  # will set 'og:description'

[params.gitalk]
  owner = "user"
  repo = "repo name"
  client_id = "your client id"
  client_secret = "your client secret"
[taxonomies]
   tag = "tags"
   category = "categories"

[params.utterances]
repo="your repo"
term="[ENTER TERM HERE]"
label="your label"
theme="github-light"

# Please visit https://giscus.app/ to generate settings.
[params.giscus]
    data_repo="mcbtaguiad/marktaguiad.dev"
    data_repo_id="R_kgDONaJdcw"    
    data_category="General"
    data_category_id="DIC_kwDONaJdc84CxJdw"
    data_mapping="pathname"
    data_strict="0"
    data_reactions_enabled="1"
    data_emit_metadata="0"
    data_input_position="bottom"
    data_theme="light"
    data_lang="en"
    crossorigin="anonymous"



[[menu.main]]
url = "/tags"
name = "Tags"
weight = 2
[[menu.main]]
url = "https://gallery.marktaguiad.dev/"
name = "Gallery"
weight = 3
[[menu.main]]
url = "/index.xml"
name = "RSS Feed"
weight = 4