name: Build-Push-Deploy-Prod

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# on:
#   workflow_dispatch:

on:
  push:
    branches: [ "gitea-dev" ]
    # Publish semver tags as releases.
    tags: [ 'v*' ]
  pull_request:
    branches: [ "gitea-dev" ]
    types: [closed]


jobs:

  build:
    # if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: repo-sync/github-to-gitea-mirror@v2
        with:
          github_repo: mcbtaguiad/marktaguiad.dev
          gitea_repo: https://gitea.marktaguiad.dev/mcbtaguiad/marktaguiad.dev.git
          gitea_token: ${{ secrets.GITEA_TOKEN }}